site_name: Wannier90 I/O with Python
site_url: https://wannier-developers.github.io/wannier90io-python
site_author: Jamal Mustafa
site_description: >-
  Wannier90 I/O with Python

repo_name: wannier-developers/wannier90io-python
repo_url: https://github.com/wannier-developers/wannier90io-python
edit_uri: ''

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_root_heading: true
            show_root_toc_entry: false
            show_signature_annotations: true
            show_source: true
            members_order: source
      watch:
        - src/wannier90io

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wannier-developers

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

nav:
  - Home: index.md
  - API Reference: api.md

watch:
  - README.md
